package com.dxhy.test.model;

public class Countrylanguage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countrylanguage.id
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countrylanguage.CountryCode
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countrylanguage.Language
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countrylanguage.No
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private Long no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countrylanguage.Percentage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private Float percentage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column countrylanguage.id
     *
     * @return the value of countrylanguage.id
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column countrylanguage.id
     *
     * @param id the value for countrylanguage.id
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column countrylanguage.CountryCode
     *
     * @return the value of countrylanguage.CountryCode
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column countrylanguage.CountryCode
     *
     * @param countryCode the value for countrylanguage.CountryCode
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column countrylanguage.Language
     *
     * @return the value of countrylanguage.Language
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column countrylanguage.Language
     *
     * @param language the value for countrylanguage.Language
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column countrylanguage.No
     *
     * @return the value of countrylanguage.No
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public Long getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column countrylanguage.No
     *
     * @param no the value for countrylanguage.No
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setNo(Long no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column countrylanguage.Percentage
     *
     * @return the value of countrylanguage.Percentage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public Float getPercentage() {
        return percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column countrylanguage.Percentage
     *
     * @param percentage the value for countrylanguage.Percentage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setPercentage(Float percentage) {
        this.percentage = percentage;
    }
}