package com.dxhy.test.model;

public class Country {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Code
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Name
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Continent
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private String continent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Region
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.SurfaceArea
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private Float surfaceArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.IndepYear
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private Short indepYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Population
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private Integer population;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.LifeExpectancy
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private Float lifeExpectancy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.GNP
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private Float GNP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.GNPOld
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private Float GNPOld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.LocalName
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private String localName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.GovernmentForm
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private String governmentForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.HeadOfState
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private String headOfState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Capital
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private Integer capital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Code2
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    private String code2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Code
     *
     * @return the value of country.Code
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Code
     *
     * @param code the value for country.Code
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Name
     *
     * @return the value of country.Name
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Name
     *
     * @param name the value for country.Name
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Continent
     *
     * @return the value of country.Continent
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public String getContinent() {
        return continent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Continent
     *
     * @param continent the value for country.Continent
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setContinent(String continent) {
        this.continent = continent == null ? null : continent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Region
     *
     * @return the value of country.Region
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Region
     *
     * @param region the value for country.Region
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.SurfaceArea
     *
     * @return the value of country.SurfaceArea
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public Float getSurfaceArea() {
        return surfaceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.SurfaceArea
     *
     * @param surfaceArea the value for country.SurfaceArea
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setSurfaceArea(Float surfaceArea) {
        this.surfaceArea = surfaceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.IndepYear
     *
     * @return the value of country.IndepYear
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public Short getIndepYear() {
        return indepYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.IndepYear
     *
     * @param indepYear the value for country.IndepYear
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setIndepYear(Short indepYear) {
        this.indepYear = indepYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Population
     *
     * @return the value of country.Population
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public Integer getPopulation() {
        return population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Population
     *
     * @param population the value for country.Population
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setPopulation(Integer population) {
        this.population = population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.LifeExpectancy
     *
     * @return the value of country.LifeExpectancy
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public Float getLifeExpectancy() {
        return lifeExpectancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.LifeExpectancy
     *
     * @param lifeExpectancy the value for country.LifeExpectancy
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setLifeExpectancy(Float lifeExpectancy) {
        this.lifeExpectancy = lifeExpectancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.GNP
     *
     * @return the value of country.GNP
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public Float getGNP() {
        return GNP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.GNP
     *
     * @param GNP the value for country.GNP
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setGNP(Float GNP) {
        this.GNP = GNP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.GNPOld
     *
     * @return the value of country.GNPOld
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public Float getGNPOld() {
        return GNPOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.GNPOld
     *
     * @param GNPOld the value for country.GNPOld
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setGNPOld(Float GNPOld) {
        this.GNPOld = GNPOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.LocalName
     *
     * @return the value of country.LocalName
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public String getLocalName() {
        return localName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.LocalName
     *
     * @param localName the value for country.LocalName
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setLocalName(String localName) {
        this.localName = localName == null ? null : localName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.GovernmentForm
     *
     * @return the value of country.GovernmentForm
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public String getGovernmentForm() {
        return governmentForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.GovernmentForm
     *
     * @param governmentForm the value for country.GovernmentForm
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setGovernmentForm(String governmentForm) {
        this.governmentForm = governmentForm == null ? null : governmentForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.HeadOfState
     *
     * @return the value of country.HeadOfState
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public String getHeadOfState() {
        return headOfState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.HeadOfState
     *
     * @param headOfState the value for country.HeadOfState
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setHeadOfState(String headOfState) {
        this.headOfState = headOfState == null ? null : headOfState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Capital
     *
     * @return the value of country.Capital
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public Integer getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Capital
     *
     * @param capital the value for country.Capital
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setCapital(Integer capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Code2
     *
     * @return the value of country.Code2
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public String getCode2() {
        return code2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Code2
     *
     * @param code2 the value for country.Code2
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    public void setCode2(String code2) {
        this.code2 = code2 == null ? null : code2.trim();
    }
}