package com.dxhy.test.dao;

import com.dxhy.test.model.Countrylanguage;
import com.dxhy.test.model.CountrylanguageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountrylanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    int countByExample(CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    int deleteByExample(CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    int insert(Countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    int insertSelective(Countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    List<Countrylanguage> selectByExample(CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    Countrylanguage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") Countrylanguage record, @Param("example") CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    int updateByExample(@Param("record") Countrylanguage record, @Param("example") CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    int updateByPrimaryKeySelective(Countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Thu May 25 17:53:09 CST 2017
     */
    int updateByPrimaryKey(Countrylanguage record);
}